# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

targetsArray = ['HHYGPUImage', 'OtherGPUImageFilter', 'SkinCareGPUImageFilter', 'RealTimeGPUImage']

targetsArray.each do |t|
  target t do
    pod 'GPUImage'
  end
  
end
